### ISSUE TITLE
unable to play a station "Your Gstreamer installation is missing a plug-in"

### ISSUE THREAD

**Issue by Fuseteam** [alexmurray/shortwave-snap#4]
i am unable to play a radio station, I get the following error:
![image](https://user-images.githubusercontent.com/10421851/193802074-88fd6258-e61d-4b02-839d-b2f6f262b3b2.png)

**Comment by alexmurray** [comment]
Thanks for reporting this issue - it should be fixed now, an updated snap is currently being built and should be available soon.

**Comment by alexmurray** [comment]
An updated snap is now available - please `sudo snap refresh shortwave` and let me know if this resolves the issue for you.

**Comment by Fuseteam** [comment]
Will do, thanks

**Comment by Fuseteam** [comment]
sorry for the delay, it indeed resolved the issue! Thank you!
