### ISSUE TITLE
3.2.0

### ISSUE THREAD

**Issue by abitrolly** [alexmurray/shortwave-snap#5]
For some reason the current snap stopped to work for me and I've noticed a new release is available https://gitlab.gnome.org/World/Shortwave/

**Comment by alexmurray** [comment]
Unfortunately the new shortwave version depends on newer versions of packages that are not available in Ubuntu 22.04 LTS (which is what the current snap is based off) and so this is not easy to update the snap to this new upstream version.

However, can you provide more details on the errors you are seeing? You mention it stopped working so I would be happy to try and help debug and resolve this for you if possible. 

Is there any output from shortwave if you run it from the command-line? Are there any errors mentioning shortwave in the dmesg output?

**Comment by abitrolly** [comment]
@alexmurray I thought `snap` benefits is that they bundle necessary packages.

There is no messages, just a blank window as if the interface doesn't render. I updated from LTS to 22.10, but nothing changed.

**Comment by abitrolly** [comment]
There is `audit: type=1326` event in `dmesg` with `syscall=314` and `code=0x50000`. If that helps.

**Comment by abitrolly** [comment]
2 hours later I tried it again, and now it launched successfully. I didn't reboot the system or reinstall it. Very strange.

**Comment by alexmurray** [comment]
> I thought `snap` benefits is that they bundle necessary packages.

They do but those dependencies have to come from somewhere - it is possible to have the snap build say a newer libadwaita from source but it doesn't currently include that hence why I can't just easily change the recipe to build the newer version - I have to also then try and update it to manually build all the newer dependencies.

> There is `audit: type=1326` event in `dmesg` with `syscall=314` and `code=0x50000`. If that helps.

This is just `sched_setattr()` which is not fatal if it doesn't succeed.


> 2 hours later I tried it again, and now it launched successfully. I didn't reboot the system or reinstall it. Very strange.

How strange indeed, but I am glad it is now working. Let's keep this issue open for the 3.2.0 version though - hopefully I get some time to look into that.

**Comment by driesdeschout** [comment]
The Gnome exension comes with its own version of libadwaita which is much more recent. I gave Shortwave 3.2.0 a go in PR #6

**Comment by alexmurray** [comment]
This has now been merged, and is available on the `latest/edge` track.
