### ISSUE TITLE
Shortwave stops music after 6 hours

### ISSUE THREAD

**Issue by KaeptnKluk** [alexmurray/shortwave-snap#9]
Hello,

does anyone know why the music in Shortwave always stops after exactly 6 hours? This happens under both Ubuntu Linux and Debian Linux. If someone has an idea, I am very grateful! Is there a configuration file where you can set something like this?

**Comment by alexmurray** [comment]
Hi - thanks for reporting this issue. I have not experienced it myself but I am not sure I have listened for more than 6 hours. Can you try running shortwave from a terminal and see if it perhaps prints anything out at this time which might give a clue as to what is going on? Thanks.

**Comment by alexmurray** [comment]
Not that I know of.
